version: '3.8'

services:
  actions-runner:
    image: ghcr.io/e4-docker/github-self-hosted-runner:latest
    environment:
      - GITHUB_ORGANIZATION=E4-Unreal
    secrets:
      - source: e4-unreal_self_hosted_runners_token
        target: actions_runner_token
    restart: unless-stopped

secrets:
  e4-unreal_self_hosted_runners_token:
    external: true
