version: '3.8'

services:
  actions-runner:
    image: ghcr.io/e4-docker/github-self-hosted-runner:latest
    environment:
      - GITHUB_ORGANIZATION
    secrets:
      - actions_runner_token
    restart: unless-stopped

secrets:
  actions_runner_token:
    external: true
